version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO_NAME: "whisper-lambda"
    DOCKERHUB_USERNAME: "03sarath"
    DEPLOY_ENV: "dev"

phases:
  pre_build:
    commands:
      - export $(grep -v '#' deploy.env | xargs)
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$MODEL_TAG
      - export LAMBDA_FUNCTION=whisper-transcribe-$DEPLOY_ENV
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr describe-repositories --repository-names $ECR_REPO_NAME --region $AWS_REGION 2>/dev/null || aws ecr create-repository --repository-name $ECR_REPO_NAME --region $AWS_REGION

  build:
    commands:
      - docker pull public.ecr.aws/x4m9m0g8/whisper-lambda:$MODEL_TAG
      - docker tag public.ecr.aws/x4m9m0g8/whisper-lambda:$MODEL_TAG $ECR_URI
      - docker push $ECR_URI

  post_build:
    commands:
      # --- Lambda: create or update test my aimlgenai-psi---
      - |
        if aws lambda get-function --function-name $LAMBDA_FUNCTION --region $AWS_REGION 2>/dev/null; then
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION --image-uri $ECR_URI --region $AWS_REGION
          aws lambda wait function-updated --function-name $LAMBDA_FUNCTION --region $AWS_REGION
          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION --timeout 900 --memory-size 3008 --region $AWS_REGION
        else
          aws lambda create-function --function-name $LAMBDA_FUNCTION --package-type Image --code ImageUri=$ECR_URI --role $LAMBDA_ROLE_ARN --timeout 900 --memory-size 3008 --region $AWS_REGION
          aws lambda wait function-active --function-name $LAMBDA_FUNCTION --region $AWS_REGION
        fi
